linters:
  enable:
    # Default linters plus these:
    - bodyclose
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gofmt
    - gosec
    - ireturn
    - makezero
    - mirror
    - misspell
    - mnd
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - paralleltest
    - revive
    - thelper
    - unconvert
    - unparam

issues:
  include:
    # Re-enable revive's doc comment linters:
    - EXC0012
    - EXC0013
    - EXC0014
    - EXC0015
  exclude-rules:
    # Pipes are best used as pre-compiled globals, much like regexp.Mustcompile()
    - text: ".*Pipe is a global variable"
      linters:
        - gochecknoglobals
    # Reflection is slow, so some global reflect types are ok
    - text: ".*Type is a global variable"
      source: ".*Type *= *reflect.TypeOf\\(.*"
      linters:
        - gochecknoglobals
    # False positive for paralleltest usage detection
    - text: "Range statement for test Test.* does not use range value in test Run"
      linters:
        - paralleltest

linters-settings:
  ireturn:
    allow:
      # Defaults:
      - anon
      - error
      - empty
      - generic
      - stdlib
      # Also allow these common interfaces:
      - github\.com\/go-git\/go-billy\/v5
      - golang\.org\/x\/tools\/godoc\/vfs

  # define the import orders
  gci:
    sections:
      # Standard section: captures all standard packages.
      - standard
      # Default section: catchall that is not standard or custom
      - default
      # linters that related to local tool, so they should be separated
      - localmodule

  misspell:
    locale: "US" # Fix the colour => color, and co