name: CD

on:
  push:
    branches: [ master ]

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Set up Go
      uses: actions/setup-go@v5.1.0
      with:
        go-version: 1.23.x
    - name: Deploy Docs
      run: make deploy-docs
      env:
        GIT_USER: ${GITHUB_ACTOR}
        GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
